services:
  arlo-downloader:
    image: "${IMAGE_VERSION:-ghcr.io/devopsx/arlo-downloader:main}"
    volumes:
      - ./records:/records
    environment:
      ARLO_USERNAME: "${ARLO_USERNAME}"
      ARLO_PASSWORD: "${ARLO_PASSWORD}"
      TFA_TYPE: "${TFA_TYPE:-EMAIL}"
      TFA_SOURCE: "${TFA_SOURCE:-imap}"
      TFA_HOST: "${TFA_HOST:-_invalid}"
      TFA_USERNAME: "${TFA_USERNAME:-_invalid}"
      TFA_PASSWORD: "${TFA_PASSWORD:-_invalid}"

      # optional
      DEBUG: ${DEBUG:-0}
      UID: ${UID:-999}
      GID: ${GID:-999}
